"""Init mode: auto-detect bucket roots and scaffold project.toml."""
from __future__ import annotations
from pathlib import Path

# Heuristic patterns for each bucket — subdir name keywords (lowercase)
NAME_HINTS: dict[str, tuple[str, ...]] = {
    "code":            ("forecasting", "code", "src", "hardware", "preprocess",
                        "fusion", "training", "models"),
    "experiment_data": ("output", "results", "experiments", "logs"),
    "paper":           ("paper_writing", "paper", "manuscript", "thesis"),
    "reading":         ("research-wiki", "reading", "papers_collected", "notes"),
    "theory":          ("theory", "derivations", "math", "notes_math"),
    "figures":         ("figures", "figs", "ppt_figures", "imgs", "plots"),
    "checkpoint_signal":("checkpoint", "checkpoints", "weights"),
}


def detect_buckets(project_root: Path) -> dict[str, list[str]]:
    """Scan top-level + 2nd-level subdirectories, classify by name hints."""
    detected: dict[str, list[str]] = {b: [] for b in NAME_HINTS}
    for sub in sorted(project_root.iterdir()):
        if not sub.is_dir() or sub.name.startswith("."):
            continue
        n = sub.name.lower()
        for bucket, hints in NAME_HINTS.items():
            if any(h in n for h in hints):
                detected[bucket].append(sub.name)
                break
    # Second pass: nested output/checkpoint/figures dirs (e.g. Forecasting/output)
    for top in sorted(project_root.iterdir()):
        if not top.is_dir() or top.name.startswith("."):
            continue
        try:
            children = list(top.iterdir())
        except (PermissionError, OSError):
            continue
        for sub in children:
            if not sub.is_dir():
                continue
            n = sub.name.lower()
            for bucket in ("experiment_data", "checkpoint_signal", "figures"):
                hints = NAME_HINTS[bucket]
                if any(h in n for h in hints):
                    rel = f"{top.name}/{sub.name}"
                    if rel not in detected[bucket]:
                        detected[bucket].append(rel)
    return detected


def build_project_toml(
    *,
    project_root: Path,
    project_name: str,
    display_name: str,
    short_name: str,
    detected: dict[str, list[str]],
) -> str:
    """Render a deterministic project.toml string from detected info."""
    def _toml_list(xs):
        return "[" + ", ".join(f'"{x}"' for x in xs) + "]"

    return f"""# Auto-generated by weekly-report-writer init at first run.
# Edit roots / ignore freely; re-run skill to pick up changes.

[project]
name = "{project_name}"
display_name = "{display_name}"
short_name = "{short_name}"
domain = ""             # one-line domain description (e.g. "雷达目标识别 / 多模态融合")
advisor = ""            # advisor title for greeting (e.g. "陈老师")
student = ""            # student name for signature (e.g. "李越")
phd_year = 1

[buckets.code]
roots = {_toml_list(detected.get('code', []))}
ignore = ["__pycache__", "dist", "build_tmp", ".pytest_cache"]
include_extensions = [".py", ".cpp", ".h", ".cu"]
content_diff_size_kb = 200
sha1_for_content_diff = true

[buckets.experiment_data]
roots = {_toml_list(detected.get('experiment_data', []))}
ignore = ["raw_data/**", "dataset/**", "*.mat", "*.npy", "*.h5"]
include_extensions = [".json", ".csv", ".tsv"]
extract_metrics = true

[buckets.paper]
roots = {_toml_list(detected.get('paper', []))}
ignore = [".aux", ".log", ".out", ".synctex.gz", "*.bak"]
include_extensions = [".tex", ".md", ".docx"]
section_diff = true

[buckets.reading]
roots = {_toml_list(detected.get('reading', []))}
include_extensions = [".md", ".pdf"]

[buckets.theory]
roots = {_toml_list(detected.get('theory', []))}
include_extensions = [".md", ".tex", ".ipynb"]
detect_math_in_paper = true
section_diff = true

[buckets.figures]
roots = {_toml_list(detected.get('figures', []))}
include_extensions = [".png", ".jpg", ".jpeg", ".svg", ".pdf"]
sample_strategy = "newest_3"
max_per_report = 5
max_size_mb = 5

[checkpoint_signal]
enabled = true
roots = {_toml_list(detected.get('checkpoint_signal', []))}
filename_patterns = [
  '_acc_(?P<acc>[\\d.]+)',
  '_epoch_?(?P<epoch>\\d+)',
  '_seed_?(?P<seed>\\d+)',
  '_loss_(?P<loss>[\\d.]+)',
]
ignore_content = true

[metrics]
hint_tokens_extra = []
config_keys_extra = []
multi_seed_aggregate = true
ci_field = "ci_95"

[scanner]
exclude_globs_global = [
  "__pycache__/**", "*.pyc", ".pytest_cache/**",
  "dist/**", "build/**", "build_tmp/**",
  ".idea/**", ".vscode/**",
  "*~", "*_tmp.*", "*_temp.*",
  ".weekly_report/**",
]
follow_symlinks = false
include_hidden = false
metadata_only_size_mb = 10
"""
