"""Target: Gemini CLI — 生成 GEMINI.md（项目根加载）"""

from __future__ import annotations

from pathlib import Path

from . import _common

GEMINI_HEADER = """<!-- This file is auto-generated by thesis-helper/compilers/build.py -->
<!-- Source: thesis-helper @ daidaoayue/SKILL -->

# GEMINI.md · thesis-helper

This file activates the **thesis-helper** workflow when Gemini CLI loads
the project. Use the `activate_skill` tool with name `thesis-helper`,
or simply mention 写论文 / 毕设 / 期刊 / conference in your prompt.

---

"""


def build(source_dir: Path, output_path: Path | None, install: bool = False) -> Path:
    if output_path is None:
        raise ValueError("gemini target requires --output")

    fm, body = _common.read_skill_md(source_dir)
    body = _common.strip_html_comments(body).strip()

    content = (
        GEMINI_HEADER
        + f"## Skill metadata\n\n"
        + f"- **Name:** {fm.get('name', 'thesis-helper')}\n"
        + f"- **Description:** {fm.get('description', '')}\n"
        + f"- **Argument hint:** {fm.get('argument-hint', '[project-dir]')}\n"
        + "\n---\n\n"
        + body
        + "\n\n---\n\n"
        + "## Gemini Tool Mapping\n\n"
        + "Claude tool names → Gemini equivalents:\n\n"
        + "| Claude | Gemini CLI |\n"
        + "|--------|------------|\n"
        + "| Read | read_file |\n"
        + "| Write | write_file |\n"
        + "| Edit | edit_file (or write_file) |\n"
        + "| Glob | list_files / search_files |\n"
        + "| Grep | grep / search_text |\n"
        + "| Bash | run_shell_command |\n"
        + "| Skill | activate_skill |\n"
    )

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    return output_path
